name: Build Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/*
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install
      run: npm install

    - name: Lint
      run: node_modules/.bin/gulp lint

  build:
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: npm install

      - name: Bundle
        run: node_modules/.bin/gulp bundle:pack

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build
          path: build/ui-bundle.zip


