name: NodeJS with Gulp

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - src/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [22.8.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp bundle:pack
        unzip build/ui-bundle.zip

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/ui-bundle
        if-no-files-found: error

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
          artifacts: build/*
            

  
