name: Pack

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - src/*
  pull_request:
    branches: [ "main" ]
    paths:
      - src/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [22.8.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Package UI Bundle
      run: |
        npm install
        node_modules/.bin/gulp
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/
        if-no-files-found: error
            
  
